# Generated by Django 6.0.1 on 2026-04-07 19:38

import delivery.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email профиля')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер'), ('courier', 'Курьер')], default='client', max_length=20, verbose_name='Роль')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', delivery.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AIChatKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'База знаний AI-чата',
                'verbose_name_plural': 'База знаний AI-чата',
                'db_table': 'ai_chat_knowledge_base',
            },
        ),
        migrations.CreateModel(
            name='CourierShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало смены')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец смены')),
                ('total_break_minutes', models.IntegerField(default=0, verbose_name='Общее время перерывов (минуты)')),
                ('orders_completed', models.IntegerField(default=0, verbose_name='Заказов выполнено за смену')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Смена курьера',
                'verbose_name_plural': 'Смены курьеров',
                'db_table': 'courier_shifts',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('documents', 'Документация'), ('gifts', 'Подарки')], max_length=20, verbose_name='Тип заказа')),
                ('tariff', models.CharField(choices=[('standard', 'Стандартный'), ('24_hours', '24 часа'), ('working', 'Рабочий'), ('fast', 'Быстрый'), ('per_hour', 'За час')], default='standard', max_length=20, verbose_name='Тариф доставки')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Вес (кг)')),
                ('client_comment', models.TextField(blank=True, verbose_name='Комментарий от клиента')),
                ('pickup_address', models.TextField(verbose_name='Адрес отправки')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('recipient_first_name', models.CharField(max_length=100, verbose_name='Имя получателя')),
                ('recipient_last_name', models.CharField(max_length=100, verbose_name='Фамилия получателя')),
                ('recipient_patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество получателя')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Телефон получателя')),
                ('recipient_company', models.CharField(blank=True, max_length=255, verbose_name='Компания получателя')),
                ('requested_delivery_date', models.DateField(verbose_name='Желаемая дата доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время доставки')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Номер счета')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает назначения'), ('assigned', 'Назначен курьер'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='created', max_length=20, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('created', 'Счет создан'), ('sent', 'Счет отправлен'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты')], default='created', max_length=20, verbose_name='Статус оплаты')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('okpo', models.CharField(blank=True, max_length=10, verbose_name='ОКПО')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('city', models.CharField(default='Москва', max_length=100, verbose_name='Город')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес')),
                ('company_phone', models.CharField(max_length=20, verbose_name='Телефон компании')),
                ('company_email', models.EmailField(max_length=254, verbose_name='E-mail компании')),
                ('bank', models.CharField(max_length=255, verbose_name='Банк')),
                ('settlement_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('contact_person_first_name', models.CharField(max_length=100, verbose_name='Имя контактного лица')),
                ('contact_person_last_name', models.CharField(max_length=100, verbose_name='Фамилия контактного лица')),
                ('contact_person_patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество контактного лица')),
                ('contact_person_phone', models.CharField(max_length=20, verbose_name='Телефон контактного лица')),
                ('contact_person_email', models.EmailField(max_length=254, verbose_name='E-mail контактного лица')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='courier_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hire_date', models.DateField(verbose_name='Дата приема на работу')),
                ('position', models.CharField(default='Курьер', max_length=255, verbose_name='Должность')),
                ('shift_status', models.CharField(choices=[('off', 'Не на смене'), ('on', 'На смене'), ('break', 'На перерыве')], default='off', max_length=10, verbose_name='Статус смены')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Всего заказов')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг')),
                ('total_work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Всего отработано часов')),
                ('total_shifts', models.IntegerField(default=0, verbose_name='Всего смен')),
                ('citizenship', models.CharField(max_length=100, verbose_name='Гражданство')),
                ('passport_series', models.CharField(max_length=4, verbose_name='Серия паспорта')),
                ('passport_number', models.CharField(max_length=6, verbose_name='Номер паспорта')),
                ('passport_department_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('passport_issued_by', models.CharField(max_length=255, verbose_name='Кем выдан')),
                ('passport_issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('registration_address', models.TextField(verbose_name='Адрес регистрации')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес проживания')),
            ],
            options={
                'verbose_name': 'Курьер',
                'verbose_name_plural': 'Курьеры',
                'db_table': 'couriers',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='manager_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(default='Менеджер', max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'db_table': 'managers',
            },
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время запроса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог AI-чата',
                'verbose_name_plural': 'Логи AI-чата',
                'db_table': 'ai_chat_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierShiftBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Начало перерыва')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец перерыва')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='delivery.couriershift')),
            ],
            options={
                'verbose_name': 'Перерыв в смене',
                'verbose_name_plural': 'Перерывы в сменах',
                'db_table': 'courier_shifts_breaks',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('pending', 'Ожидает назначения'), ('assigned', 'Назначен курьер'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], max_length=20, verbose_name='Статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='delivery.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статуса',
                'verbose_name_plural': 'История статусов',
                'db_table': 'order_status_history',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Счет создан'), ('sent', 'Счет отправлен'), ('paid', 'Оплачено'), ('failed', 'Ошибка оплаты')], default='created', max_length=20, verbose_name='Статус оплаты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Чек')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания счета')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='delivery.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='delivery.client', verbose_name='Клиент'),
        ),
        migrations.CreateModel(
            name='ClientAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий от менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='delivery.client')),
            ],
            options={
                'verbose_name': 'Доп. информация о клиенте',
                'verbose_name_plural': 'Доп. информация о клиентах',
                'db_table': 'clients_additional_info',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала отпуска')),
                ('end_date', models.DateField(verbose_name='Дата окончания отпуска')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacations', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Отпуск',
                'verbose_name_plural': 'Отпуска',
                'db_table': 'vacations',
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала болезни')),
                ('end_date', models.DateField(verbose_name='Дата окончания болезни')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sick_leaves', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Больничный лист',
                'verbose_name_plural': 'Больничные листы',
                'db_table': 'sick_leaves',
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='delivery.order', verbose_name='Заказ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='delivery.client', verbose_name='Клиент')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='delivery.courier', verbose_name='Курьер')),
            ],
            options={
                'verbose_name': 'Оценка заказа',
                'verbose_name_plural': 'Оценки заказов',
                'db_table': 'order_ratings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.courier', verbose_name='Курьер'),
        ),
        migrations.AddField(
            model_name='couriershift',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='delivery.courier'),
        ),
        migrations.CreateModel(
            name='CourierAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий от менеджера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='delivery.courier')),
            ],
            options={
                'verbose_name': 'Доп. информация о курьере',
                'verbose_name_plural': 'Доп. информация о курьерах',
                'db_table': 'couriers_additional_info',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to='delivery.manager', verbose_name='Менеджер'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_status_11db6c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'status'], name='orders_client__2e756d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['courier', 'status'], name='orders_courier_17fae5_idx'),
        ),
    ]
