# Generated by Django 6.0.1 on 2026-04-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('notification_type', models.CharField(choices=[('new', 'Новый заказ'), ('reminder', 'Напоминание'), ('rejected', 'Отклонен')], default='new', max_length=20)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='delivery.courier')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='delivery.order')),
            ],
            options={
                'verbose_name': 'Уведомление курьера',
                'verbose_name_plural': 'Уведомления курьеров',
                'db_table': 'courier_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
