# Generated by Django 6.0.1 on 2026-01-13 21:22

import delivery.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', delivery.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house',
            field=models.CharField(max_length=20, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.ordertype', verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(max_length=255, verbose_name='Улица'),
        ),
    ]
