# Generated by Django 6.0.1 on 2026-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_couriernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt',
        ),
        migrations.AddField(
            model_name='courier',
            name='work_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Конец рабочего дня'),
        ),
        migrations.AddField(
            model_name='courier',
            name='work_slot',
            field=models.CharField(choices=[('morning', '09:00 - 12:00 (утро)'), ('day', '12:00 - 15:00 (день)'), ('afternoon', '15:00 - 18:00 (вечер)'), ('full', '09:00 - 18:00 (полный день)'), ('custom', 'Индивидуальный график')], default='full', max_length=20, verbose_name='Предпочитаемое время работы'),
        ),
        migrations.AddField(
            model_name='courier',
            name='work_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Начало рабочего дня'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Желаемое время доставки (конкретное)'),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_time_slot',
            field=models.CharField(choices=[('morning', '09:00 - 12:00'), ('day', '12:00 - 15:00'), ('afternoon', '15:00 - 18:00'), ('evening', '18:00 - 21:00'), ('any', 'Весь день')], default='any', max_length=20, verbose_name='Желаемое время доставки'),
        ),
    ]
