# Generated by Django 6.0.1 on 2026-04-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_payment_receipt_courier_work_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('documents', 'Документация'), ('gifts', 'Корпоративные поздравления')], max_length=20, verbose_name='Тип заказа'),
        ),
    ]
