# Generated by Django 6.0.1 on 2026-04-29 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('occasion', models.CharField(choices=[('gift', 'Подарок клиентам'), ('pr', 'PR-рассылка'), ('other', 'Другое')], max_length=20, verbose_name='Повод')),
                ('pickup_address', models.TextField(verbose_name='Адрес забора')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к кампании')),
                ('delivery_mode', models.CharField(choices=[('one_day', 'Все в один день'), ('within_week', 'В течение недели'), ('custom', 'Выбрать дату')], default='one_day', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Желаемая дата доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('delivered_count', models.IntegerField(default=0)),
                ('in_progress_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='delivery.client')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Компания')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('assigned', 'Назначен курьер'), ('in_progress', 'В пути'), ('delivered', 'Доставлен'), ('error', 'Ошибка адреса')], default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='delivery.campaign')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.courier')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipient', to='delivery.order')),
            ],
        ),
    ]
